## Homework 2

A child has available a certain number of ice cream scoops every day, s. The child can store a number of scoops for the next day a and eat the remainder scoops c = s − a. The number of scoops available the next day, s′, is equal to the number of scoops stored over night, a, plus an additional scoops provided by the parents, e. The number of scoops available the next day is given by:

s' = a + e'

s' = (s-c) + e'

e' must be known after the decision "a" is made. 

The child can store up to 2 scoops in the fridge every day which implies that a ∈ {0, 1, 2} and s ∈ {0, 1, 2, 3, 4}.

#### Necessary imports

In [56]:
import sys
import pandas as pd
import numpy as np

np.set_printoptions(threshold=sys.maxsize)

# enable ability to see the value of multiple statements at once
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#### The transition probability matrix from e to e′ is given by:

In [2]:
Pt_e = np.array(
            [[0.8, 0.1, 0.1],
               [0.01, 0.98, 0.01],
               [0.1, 0.1, 0.8]])

Pt_e

array([[0.8 , 0.1 , 0.1 ],
       [0.01, 0.98, 0.01],
       [0.1 , 0.1 , 0.8 ]])

#### 1) Construct the transition probability from (s, e) to (s′, e′) for each action a ∈ {0, 1, 2}.

In [3]:
col_name = []

for s in range(5):
    for e in range(3):
        col_name.append((s,e))

# prepare (s, e) column names
col_name 

[(0, 0),
 (0, 1),
 (0, 2),
 (1, 0),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 1),
 (2, 2),
 (3, 0),
 (3, 1),
 (3, 2),
 (4, 0),
 (4, 1),
 (4, 2)]

In [4]:
# return 15 x 15 array without initializing entries
Pt_se = np.empty((15,15))

# fill with NaNs
Pt_se[:] = np.nan

# overlay column names
Pt_se_df = pd.DataFrame(Pt_se, columns=col_name, index=col_name)

# preview result
Pt_se_df

(0, 0)  (0, 1)  (0, 2)  (1, 0)  (1, 1)  (1, 2)  (2, 0)  (2, 1)  \
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

        (2, 2)  (3, 0)  (3, 1)  (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [5]:
# given e cannot be larger than s, as s = s(t=t-1) + e, therefore, the probability of transitioning from (s,e) 
# where s < e should be 0


# loop through (s, e) and (s', e') to eliminate rows with 0 probability

for (s,e) in col_name:
    if s < e:
        Pt_se_df.drop([(s,e)],inplace=True)
        
Pt_se_df

(0, 0)  (0, 1)  (0, 2)  (1, 0)  (1, 1)  (1, 2)  (2, 0)  (2, 1)  \
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

        (2, 2)  (3, 0)  (3, 1)  (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [6]:
# loop through (s, e) and (s', e') to eliminate columns with 0 probability

for(s_,e_) in col_name: 
    if s_ < e_:
        Pt_se_df.drop(columns=[(s_,e_)], inplace=True)  
        
Pt_se_df

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     NaN     NaN     NaN     NaN  
(1, 0)     NaN     NaN     NaN     NaN  
(1, 1)     NaN     NaN     NaN     NaN  
(2, 0)     NaN     NaN     NaN     NaN  
(2, 1)     NaN     NaN     NaN     NaN  
(2, 2)     NaN     NaN     NaN     NaN  
(3, 0)     NaN     NaN     NaN     NaN  
(3, 1)     NaN     NaN     NaN     NaN  
(3, 2)     NaN     NaN     NaN     NaN  
(4, 0)     NaN     NaN     NaN     NaN  
(4, 1)     NaN     NaN     NaN     NaN  
(4, 2)     NaN     NaN     NaN     NaN

In [9]:
# view revised list of states after elimination of rows & cols w/ 0 probability
col_name = list(Pt_se_df)
col_name

# review corresponding revised matrix, which is now a 12 x 12
Pt_se_df

[(0, 0),
 (1, 0),
 (1, 1),
 (2, 0),
 (2, 1),
 (2, 2),
 (3, 0),
 (3, 1),
 (3, 2),
 (4, 0),
 (4, 1),
 (4, 2)]

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     NaN     NaN     NaN     NaN  
(1, 0)     NaN     NaN     NaN     NaN  
(1, 1)     NaN     NaN     NaN     NaN  
(2, 0)     NaN     NaN     NaN     NaN  
(2, 1)     NaN     NaN     NaN     NaN  
(2, 2)     NaN     NaN     NaN     NaN  
(3, 0)     NaN     NaN     NaN     NaN  
(3, 1)     NaN     NaN     NaN     NaN  
(3, 2)     NaN     NaN     NaN     NaN  
(4, 0)     NaN     NaN     NaN     NaN  
(4, 1)     NaN     NaN     NaN     NaN  
(4, 2)     NaN     NaN     NaN     NaN

In [10]:
# create a copy of transition probability matrix for analysis of each action a ∈ {0, 1, 2}
Pt_se_df_0 = Pt_se_df.copy()
Pt_se_df_1 = Pt_se_df.copy()
Pt_se_df_2 = Pt_se_df.copy()

For a = 0, s' must be equal to e', so probability of transitioning to (s',e') where s' != e' should be 0

In [11]:
# looping through (s', e') columns

for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_:
        Pt_se_df_0.loc[:, (s_,e_)] = 0

        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_0.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_0.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            

# view result
Pt_se_df_0

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)    0.80       0    0.10       0       0    0.10       0       0   
(1, 0)    0.80       0    0.10       0       0    0.10       0       0   
(1, 1)    0.01       0    0.98       0       0    0.01       0       0   
(2, 0)    0.80       0    0.10       0       0    0.10       0       0   
(2, 1)    0.01       0    0.98       0       0    0.01       0       0   
(2, 2)    0.10       0    0.10       0       0    0.80       0       0   
(3, 0)    0.80       0    0.10       0       0    0.10       0       0   
(3, 1)    0.01       0    0.98       0       0    0.01       0       0   
(3, 2)    0.10       0    0.10       0       0    0.80       0       0   
(4, 0)    0.80       0    0.10       0       0    0.10       0       0   
(4, 1)    0.01       0    0.98       0       0    0.01       0       0   
(4, 2)    0.10       0    0.10       0       0    0.80       0       0   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)       0       0       0       0  
(1, 0)       0       0       0       0  
(1, 1)       0       0       0       0  
(2, 0)       0       0       0       0  
(2, 1)       0       0       0       0  
(2, 2)       0       0       0       0  
(3, 0)       0       0       0       0  
(3, 1)       0       0       0       0  
(3, 2)       0       0       0       0  
(4, 0)       0       0       0       0  
(4, 1)       0       0       0       0  
(4, 2)       0       0       0       0

For a = 1, s' must be equal to e', therefore, probability on transitioning to (s',e') where s' != e' + 1 should be 0.

In [13]:
# looping through (s', e')
for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_ + 1:
        Pt_se_df_1.loc[:, (s_,e_)] = 0
        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_1.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_1.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            
# view result        
Pt_se_df_1

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)       0    0.80       0       0    0.10       0       0       0   
(1, 0)       0    0.80       0       0    0.10       0       0       0   
(1, 1)       0    0.01       0       0    0.98       0       0       0   
(2, 0)       0    0.80       0       0    0.10       0       0       0   
(2, 1)       0    0.01       0       0    0.98       0       0       0   
(2, 2)       0    0.10       0       0    0.10       0       0       0   
(3, 0)       0    0.80       0       0    0.10       0       0       0   
(3, 1)       0    0.01       0       0    0.98       0       0       0   
(3, 2)       0    0.10       0       0    0.10       0       0       0   
(4, 0)       0    0.80       0       0    0.10       0       0       0   
(4, 1)       0    0.01       0       0    0.98       0       0       0   
(4, 2)       0    0.10       0       0    0.10       0       0       0   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)    0.10       0       0       0  
(1, 0)    0.10       0       0       0  
(1, 1)    0.01       0       0       0  
(2, 0)    0.10       0       0       0  
(2, 1)    0.01       0       0       0  
(2, 2)    0.80       0       0       0  
(3, 0)    0.10       0       0       0  
(3, 1)    0.01       0       0       0  
(3, 2)    0.80       0       0       0  
(4, 0)    0.10       0       0       0  
(4, 1)    0.01       0       0       0  
(4, 2)    0.80       0       0       0

For a = 2, s' must be equal to e', therefore, probability on transitioning to (s',e') where s' != e' + 2 should be 0.

In [15]:
#looping through (s', e')
for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_ + 2:
        Pt_se_df_2.loc[:, (s_,e_)] = 0
        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_2.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_2.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            
            
# view result
Pt_se_df_2

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)       0       0       0    0.80       0       0       0    0.10   
(1, 0)       0       0       0    0.80       0       0       0    0.10   
(1, 1)       0       0       0    0.01       0       0       0    0.98   
(2, 0)       0       0       0    0.80       0       0       0    0.10   
(2, 1)       0       0       0    0.01       0       0       0    0.98   
(2, 2)       0       0       0    0.10       0       0       0    0.10   
(3, 0)       0       0       0    0.80       0       0       0    0.10   
(3, 1)       0       0       0    0.01       0       0       0    0.98   
(3, 2)       0       0       0    0.10       0       0       0    0.10   
(4, 0)       0       0       0    0.80       0       0       0    0.10   
(4, 1)       0       0       0    0.01       0       0       0    0.98   
(4, 2)       0       0       0    0.10       0       0       0    0.10   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)       0       0       0    0.10  
(1, 0)       0       0       0    0.10  
(1, 1)       0       0       0    0.01  
(2, 0)       0       0       0    0.10  
(2, 1)       0       0       0    0.01  
(2, 2)       0       0       0    0.80  
(3, 0)       0       0       0    0.10  
(3, 1)       0       0       0    0.01  
(3, 2)       0       0       0    0.80  
(4, 0)       0       0       0    0.10  
(4, 1)       0       0       0    0.01  
(4, 2)       0       0       0    0.80

#### 2) The child subjected utility from eating ice cream is log( c + 1) if c ≥ 0 and −∞ otherwise.  Construct the reward matrix for each transition (s, e, a) and (s′, e′).

In [20]:
# construct reward function
def reward(c):
    if c >= 0:
        return np.log(c + 1)
    else:
        return np.NINF
    

# apply function to get (s, e, a) combos
reward_row = []

for a in range(3):
    for (s,e) in col_name:
        reward_row.append((s,e,a))
 
# view result
reward_row

[(0, 0, 0),
 (1, 0, 0),
 (1, 1, 0),
 (2, 0, 0),
 (2, 1, 0),
 (2, 2, 0),
 (3, 0, 0),
 (3, 1, 0),
 (3, 2, 0),
 (4, 0, 0),
 (4, 1, 0),
 (4, 2, 0),
 (0, 0, 1),
 (1, 0, 1),
 (1, 1, 1),
 (2, 0, 1),
 (2, 1, 1),
 (2, 2, 1),
 (3, 0, 1),
 (3, 1, 1),
 (3, 2, 1),
 (4, 0, 1),
 (4, 1, 1),
 (4, 2, 1),
 (0, 0, 2),
 (1, 0, 2),
 (1, 1, 2),
 (2, 0, 2),
 (2, 1, 2),
 (2, 2, 2),
 (3, 0, 2),
 (3, 1, 2),
 (3, 2, 2),
 (4, 0, 2),
 (4, 1, 2),
 (4, 2, 2)]

In [25]:
# return 36 X 12 array without initializing entries
R_sea = np.empty((len(reward_row),len(col_name)))

# fill with NaNs
R_sea[:] = np.nan

# overlay column names
R_sea_df = pd.DataFrame(R_sea, columns=col_name, index=reward_row)

# view result
R_sea_df

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2, 0)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(0, 0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2, 1)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(0, 0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(1, 1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(2, 2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(3, 2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 0, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 1, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
(4, 2, 2)     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

           (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0, 0)     NaN     NaN     NaN     NaN  
(1, 0, 0)     NaN     NaN     NaN     NaN  
(1, 1, 0)     NaN     NaN     NaN     NaN  
(2, 0, 0)     NaN     NaN     NaN     NaN  
(2, 1, 0)     NaN     NaN     NaN     NaN  
(2, 2, 0)     NaN     NaN     NaN     NaN  
(3, 0, 0)     NaN     NaN     NaN     NaN  
(3, 1, 0)     NaN     NaN     NaN     NaN  
(3, 2, 0)     NaN     NaN     NaN     NaN  
(4, 0, 0)     NaN     NaN     NaN     NaN  
(4, 1, 0)     NaN     NaN     NaN     NaN  
(4, 2, 0)     NaN     NaN     NaN     NaN  
(0, 0, 1)     NaN     NaN     NaN     NaN  
(1, 0, 1)     NaN     NaN     NaN     NaN  
(1, 1, 1)     NaN     NaN     NaN     NaN  
(2, 0, 1)     NaN     NaN     NaN     NaN  
(2, 1, 1)     NaN     NaN     NaN     NaN  
(2, 2, 1)     NaN     NaN     NaN     NaN  
(3, 0, 1)     NaN     NaN     NaN     NaN  
(3, 1, 1)     NaN     NaN     NaN     NaN  
(3, 2, 1)     NaN     NaN     NaN     NaN  
(4, 0, 1)     NaN     NaN     NaN     NaN  
(4, 1, 1)     NaN     NaN     NaN     NaN  
(4, 2, 1)     NaN     NaN     NaN     NaN  
(0, 0, 2)     NaN     NaN     NaN     NaN  
(1, 0, 2)     NaN

In [28]:
# apply reward function 

# reward is dependent on availability of ice cream, s, at the initial state
for (s,e,a) in reward_row:
    c = s - a
    R_sea_df.loc[(s,e,a),:] = reward(c)
    
# view result
R_sea_df

(0, 0)    (1, 0)    (1, 1)    (2, 0)    (2, 1)    (2, 2)  \
(0, 0, 0)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(1, 0, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(1, 1, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(2, 0, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(2, 1, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(2, 2, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(3, 0, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(3, 1, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(3, 2, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(4, 0, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   
(4, 1, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   
(4, 2, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   
(0, 0, 1)      -inf      -inf      -inf      -inf      -inf      -inf   
(1, 0, 1)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(1, 1, 1)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(2, 0, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(2, 1, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(2, 2, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(3, 0, 1)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(3, 1, 1)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(3, 2, 1)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(4, 0, 1)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(4, 1, 1)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(4, 2, 1)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(0, 0, 2)      -inf      -inf      -inf      -inf      -inf      -inf   
(1, 0, 2)      -inf      -inf      -inf      -inf      -inf      -inf   
(1, 1, 2)      -inf      -inf      -inf      -inf      -inf      -inf   
(2, 0, 2)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(2, 1, 2)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(2, 2, 2)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(3, 0, 2)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(3, 1, 2)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(3, 2, 2)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(4, 0, 2)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(4, 1, 2)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(4, 2, 2)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   

             (3, 0)    (3, 1)    (3, 2)    (4, 0)    (4, 1)    (4, 2)  
(0, 0, 0)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
(1, 0, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  
(1, 1, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  
(2, 0, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  
(2, 1, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  
(2, 2, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  
(3, 0, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  
(3, 1, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  
(3, 2, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  
(4, 0, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  
(4, 1, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  
(4, 2, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  
(0, 0, 1)      -inf      -inf      -inf      -inf      -inf      -inf  
(1, 0, 1)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
(1, 1, 1)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
(2, 0, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  
(2, 1, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  
(2, 2, 1)  0.69

In [30]:
# create a copy of transition probability matrix for analysis of rewards for each action a∈{0, 1, 2}
R_se_df_0 = Pt_se_df.copy()
R_se_df_1 = Pt_se_df.copy()
R_se_df_2 = Pt_se_df.copy()

In [31]:
# reward matrix for all values for a
# eating all the ice cream is (s = c)

a = 0
for (s,e) in col_name:
    c = s - a
    R_se_df_0.loc[(s,e),:] = reward(c)
      
a = 1
for (s,e) in col_name:
    c = s - a
    R_se_df_1.loc[(s,e),:] = reward(c)

a = 2
for (s,e) in col_name:
    c = s - a
    R_se_df_2.loc[(s,e),:] = reward(c)

In [32]:
R_se_df_0

(0, 0)    (1, 0)    (1, 1)    (2, 0)    (2, 1)    (2, 2)    (3, 0)  \
(0, 0)  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
(1, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(1, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147  0.693147   
(2, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(2, 1)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(2, 2)  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612  1.098612   
(3, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(3, 1)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(3, 2)  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294  1.386294   
(4, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   
(4, 1)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   
(4, 2)  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438  1.609438   

          (3, 1)    (3, 2)    (4, 0)    (4, 1)    (4, 2)  
(0, 0)  0.000000  0.000000  0.000000  0.000000  0.000000  
(1, 0)  0.693147  0.693147  0.693147  0.693147  0.693147  
(1, 1)  0.693147  0.693147  0.693147  0.693147  0.693147  
(2, 0)  1.098612  1.098612  1.098612  1.098612  1.098612  
(2, 1)  1.098612  1.098612  1.098612  1.098612  1.098612  
(2, 2)  1.098612  1.098612  1.098612  1.098612  1.098612  
(3, 0)  1.386294  1.386294  1.386294  1.386294  1.386294  
(3, 1)  1.386294  1.386294  1.386294  1.386294  1.386294  
(3, 2)  1.386294  1.386294  1.386294  1.386294  1.386294  
(4, 0)  1.609438  1.609438  1.609438  1.609438  1.609438  
(4, 1)  1.609438  1.609438  1.609438  1.609438  1.609438  
(4, 2)  1.609438  1.609438  1.609438  1.609438  1.609438

In [43]:
# combine all transition probabilities into one array
P = np.array([Pt_se_df_0, Pt_se_df_1, Pt_se_df_2],dtype=float)
P.shape

P

K,N,M = P.shape

(3, 12, 2)

array([[[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]]])

In [36]:
# combine all rewards into one array
RR = np.array([R_se_df_0, R_se_df_1, R_se_df_2],dtype=float)
RR.shape

RR

(3, 12, 2)

array([[[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]]])

#### 3) Apply the value iteration approach to compute the value function for each state and optimal policy. Iterate 600 times.

In [46]:
# compute the expected reward (immediate)

q = np.zeros((K,N,1),dtype=np.float64) # create three 12 x 1 arrays
q.shape


# loop through each (K,N,M) array

for i in range(0,N): # N is 12
    for k in range(0,K): # K is 3
        for j in range(0,M): # M is 2
            q[k,i,0] = q[k,i,0] + RR[k,i,j]*P[k,i,j]

# view result
q

array([[[ 0.],
        [ 2.],
        [ 4.],
        [ 8.],
        [10.],
        [16.],
        [18.],
        [20.],
        [26.],
        [32.],
        [34.],
        [40.]],

       [[ 0.],
        [ 2.],
        [ 4.],
        [ 8.],
        [10.],
        [16.],
        [18.],
        [20.],
        [26.],
        [32.],
        [34.],
        [40.]],

       [[ 0.],
        [ 2.],
        [ 4.],
        [ 8.],
        [10.],
        [16.],
        [18.],
        [20.],
        [26.],
        [32.],
        [34.],
        [40.]]])

In [60]:
# number of episodes
T = 600

# value table
v = np.zeros((N,T),dtype=np.float64) # N is 12
v.shape
v

# decisions table
d = np.zeros((N,T),dtype=np.float64)
d.shape
d

(12, 600)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(12, 600)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [61]:
for n in range(1,T): # T is 600
    for i in range(0,N): # N is 12
        
        # rhs should be 1 x 3 and will initially be all zeroes
        rhs = np.zeros((1,K),dtype=np.float64) # K is 3
        
        for k in range(0,K): # K is 3
            rhs[0][k] = q[k][i][0] + np.matmul(P[k,i,:],v[:,n-1]) 
        
        v[i,n] = max(rhs[0])
        d[i,n] = np.argmax(rhs[0])

array([[0., 0., 0.]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 2)

In [55]:
# value table
v = v.T
v

# decisions table
d = d.T
d

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [62]:
policy_df = pd.DataFrame(d, columns=col_name)
policy_df

ValueError: Shape of passed values is (12, 600), indices imply (12, 12)

#### 4) For each e, plot the value function v(s, e) with s on the x-axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

In [ ]:
# take values at bottom of value table you calculate in three for the (s, e) pairs.
# look up the value for the different states and scoops given combinations
value_data = pd.DataFrame({'s': range(5),
                          'zero': [],
                          'one': [],
                          'two': []})

In [ ]:
plt.plot('s', 'zero', data = value_data, color = 'darkred')
plt.plot('s', 'one', data = value_data, color = 'gold')
plt.plot('s', 'two', data = value_data, color = 'green')

plt.legend()
plt.title('Value function by state for each possible scoops given')

#### 5) For each e, plot the optimal policy for storing ice cream scoops a(s, e) with s on the x- axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

#### 6) For each e, plot the optimal policy for consuming ice cream scoops c(s, e) with s on the x-axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

#### 7) Simulate a sequence of e and set an initial value for s. Given the optimal policy, calculate and plot the evolution of a, c, and s over time.

#### 8) Construct the transition probability and reward matrices between (s, e) and (s′, e′) that produces the highest expected discount rewards. (hint: you need to use the optimal policy)

#### 9) Calculate the value function for the Markok process with rewards that produces the highest expected discount rewards. (hint: use the transition probability and reward matrices from the previous question). Does the value function matches reasonably the value function from the previous question? (hint: it should)

#### 10) Simulate the Markov process with rewards from the previous question for starting at each state pair (e, s). Compute the average discounted reward. Does it match reasonabily close to the value function in the previous question? (hint: it should)

#### 11) Calculate the optimal policy based on the policy iteration approach.