<div>
<img src="https://lh3.googleusercontent.com/proxy/tO6E7mzeltZO1RKOLGM9UV-a7U9qazRXKtCsAQLS-pj-mDYX3pwC3Dpq3xUYgzPRSZj_HMeXS85GfV0DciAH_CZHjZyxstV7KzDY1OBPsvpGkKjJ4Ij7hBMdlnxujHoJ6rkgi6igBqy_EmpeOkOD8o8UTH7R-nFakk6_2_9yAvpfKF1xWmbBwY4kClJtxSoUxVdo-eYu102Bam5MFl-5uaC5cObRmACTkkbxcw" width="200" align="left"/>
</div>



## Homework 2

A child has available a certain number of ice cream scoops every day, 's'. The child can store a number of scoops for the next day 'a' and eat the remainder scoops c = s − a. The number of scoops available the next day, s′, is equal to the number of scoops stored over night, a, plus an additional scoops provided by the parents, e. The number of scoops available the next day is given by:

s' = a + e'

s' = (s-c) + e'

e' must be known after the decision "a" is made. 

The child can store up to 2 scoops in the fridge every day which implies that a ∈ {0, 1, 2}, s ∈ {0, 1, 2, 3, 4} & e
∈ {0,1,2}.



#### Necessary imports

In [30]:
import sys
import pandas as pd
import numpy as np

pd.set_option('display.float_format', lambda x: '%.5f' % x)

np.set_printoptions(threshold=sys.maxsize)

# enable ability to see the value of multiple statements at once
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#### The transition probability matrix from e to e′ is given by:

In [31]:
Pt_e = np.array(
            [[0.8, 0.1, 0.1],
            [0.01, 0.98, 0.01],
            [0.1, 0.1, 0.8]]
)

Pt_e

array([[0.8 , 0.1 , 0.1 ],
       [0.01, 0.98, 0.01],
       [0.1 , 0.1 , 0.8 ]])

#### 1) Construct the transition probability from (s, e) to (s′, e′) for each action a ∈ {0, 1, 2}.

In [32]:
col_name = []

for s in range(5):
    for e in range(3):
        col_name.append((s,e))

# prepare (s, e) column names
col_name 

[(0, 0),
 (0, 1),
 (0, 2),
 (1, 0),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 1),
 (2, 2),
 (3, 0),
 (3, 1),
 (3, 2),
 (4, 0),
 (4, 1),
 (4, 2)]

In [33]:
# return 15 x 15 array without initializing entries
Pt_se = np.empty((15,15))

# fill with NaNs
Pt_se[:] = np.nan

# overlay column names
Pt_se_df = pd.DataFrame(Pt_se, columns=col_name, index=col_name)

# preview result
Pt_se_df

(0, 0)  (0, 1)  (0, 2)  (1, 0)  (1, 1)  (1, 2)  (2, 0)  (2, 1)  \
(0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2)     nan     nan     nan     nan     nan     nan     nan     nan   

        (2, 2)  (3, 0)  (3, 1)  (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     nan     nan     nan     nan     nan     nan     nan  
(0, 1)     nan     nan     nan     nan     nan     nan     nan  
(0, 2)     nan     nan     nan     nan     nan     nan     nan  
(1, 0)     nan     nan     nan     nan     nan     nan     nan  
(1, 1)     nan     nan     nan     nan     nan     nan     nan  
(1, 2)     nan     nan     nan     nan     nan     nan     nan  
(2, 0)     nan     nan     nan     nan     nan     nan     nan  
(2, 1)     nan     nan     nan     nan     nan     nan     nan  
(2, 2)     nan     nan     nan     nan     nan     nan     nan  
(3, 0)     nan     nan     nan     nan     nan     nan     nan  
(3, 1)     nan     nan     nan     nan     nan     nan     nan  
(3, 2)     nan     nan     nan     nan     nan     nan     nan  
(4, 0)     nan     nan     nan     nan     nan     nan     nan  
(4, 1)     nan     nan     nan     nan     nan     nan     nan  
(4, 2)     nan     nan     nan     nan     nan     nan     nan

In [34]:
# given e cannot be larger than s, as s = s(t=t-1) + e, therefore, the probability of transitioning from (s,e) 
# where s < e should be 0


# loop through (s, e) and (s', e') to eliminate rows with 0 probability

for (s,e) in col_name:
    if s < e:
        Pt_se_df.drop([(s,e)], inplace = True)
        
Pt_se_df

(0, 0)  (0, 1)  (0, 2)  (1, 0)  (1, 1)  (1, 2)  (2, 0)  (2, 1)  \
(0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2)     nan     nan     nan     nan     nan     nan     nan     nan   

        (2, 2)  (3, 0)  (3, 1)  (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     nan     nan     nan     nan     nan     nan     nan  
(1, 0)     nan     nan     nan     nan     nan     nan     nan  
(1, 1)     nan     nan     nan     nan     nan     nan     nan  
(2, 0)     nan     nan     nan     nan     nan     nan     nan  
(2, 1)     nan     nan     nan     nan     nan     nan     nan  
(2, 2)     nan     nan     nan     nan     nan     nan     nan  
(3, 0)     nan     nan     nan     nan     nan     nan     nan  
(3, 1)     nan     nan     nan     nan     nan     nan     nan  
(3, 2)     nan     nan     nan     nan     nan     nan     nan  
(4, 0)     nan     nan     nan     nan     nan     nan     nan  
(4, 1)     nan     nan     nan     nan     nan     nan     nan  
(4, 2)     nan     nan     nan     nan     nan     nan     nan

In [35]:
# loop through (s, e) and (s', e') to eliminate columns with 0 probability

for(s_,e_) in col_name: 
    if s_ < e_:
        Pt_se_df.drop(columns=[(s_,e_)], inplace = True)  
        
Pt_se_df

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2)     nan     nan     nan     nan     nan     nan     nan     nan   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     nan     nan     nan     nan  
(1, 0)     nan     nan     nan     nan  
(1, 1)     nan     nan     nan     nan  
(2, 0)     nan     nan     nan     nan  
(2, 1)     nan     nan     nan     nan  
(2, 2)     nan     nan     nan     nan  
(3, 0)     nan     nan     nan     nan  
(3, 1)     nan     nan     nan     nan  
(3, 2)     nan     nan     nan     nan  
(4, 0)     nan     nan     nan     nan  
(4, 1)     nan     nan     nan     nan  
(4, 2)     nan     nan     nan     nan

In [36]:
# view revised list of states after elimination of rows & cols w/ 0 probability
col_name = list(Pt_se_df)
col_name

# review corresponding revised matrix, which is now a 12 x 12
Pt_se_df

[(0, 0),
 (1, 0),
 (1, 1),
 (2, 0),
 (2, 1),
 (2, 2),
 (3, 0),
 (3, 1),
 (3, 2),
 (4, 0),
 (4, 1),
 (4, 2)]

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2)     nan     nan     nan     nan     nan     nan     nan     nan   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)     nan     nan     nan     nan  
(1, 0)     nan     nan     nan     nan  
(1, 1)     nan     nan     nan     nan  
(2, 0)     nan     nan     nan     nan  
(2, 1)     nan     nan     nan     nan  
(2, 2)     nan     nan     nan     nan  
(3, 0)     nan     nan     nan     nan  
(3, 1)     nan     nan     nan     nan  
(3, 2)     nan     nan     nan     nan  
(4, 0)     nan     nan     nan     nan  
(4, 1)     nan     nan     nan     nan  
(4, 2)     nan     nan     nan     nan

In [37]:
# create a copy of transition probability matrix for analysis of each action a ∈ {0, 1, 2}
Pt_se_df_0 = Pt_se_df.copy()
Pt_se_df_1 = Pt_se_df.copy()
Pt_se_df_2 = Pt_se_df.copy()

For a = 0, s' must be equal to e', so probability of transitioning to (s',e') where s' != e' should be 0

In [38]:
# looping through (s', e') columns

for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_:
        Pt_se_df_0.loc[:, (s_,e_)] = 0

        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_0.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_0.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            

# view result
Pt_se_df_0

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0) 0.80000       0 0.10000       0       0 0.10000       0       0   
(1, 0) 0.80000       0 0.10000       0       0 0.10000       0       0   
(1, 1) 0.01000       0 0.98000       0       0 0.01000       0       0   
(2, 0) 0.80000       0 0.10000       0       0 0.10000       0       0   
(2, 1) 0.01000       0 0.98000       0       0 0.01000       0       0   
(2, 2) 0.10000       0 0.10000       0       0 0.80000       0       0   
(3, 0) 0.80000       0 0.10000       0       0 0.10000       0       0   
(3, 1) 0.01000       0 0.98000       0       0 0.01000       0       0   
(3, 2) 0.10000       0 0.10000       0       0 0.80000       0       0   
(4, 0) 0.80000       0 0.10000       0       0 0.10000       0       0   
(4, 1) 0.01000       0 0.98000       0       0 0.01000       0       0   
(4, 2) 0.10000       0 0.10000       0       0 0.80000       0       0   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)       0       0       0       0  
(1, 0)       0       0       0       0  
(1, 1)       0       0       0       0  
(2, 0)       0       0       0       0  
(2, 1)       0       0       0       0  
(2, 2)       0       0       0       0  
(3, 0)       0       0       0       0  
(3, 1)       0       0       0       0  
(3, 2)       0       0       0       0  
(4, 0)       0       0       0       0  
(4, 1)       0       0       0       0  
(4, 2)       0       0       0       0

For a = 1, s' must be equal to e', therefore, probability on transitioning to (s',e') where s' != e' + 1 should be 0.

In [39]:
# looping through (s', e')
for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_ + 1:
        Pt_se_df_1.loc[:, (s_,e_)] = 0
        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_1.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_1.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            
# view result        
Pt_se_df_1

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)       0 0.80000       0       0 0.10000       0       0       0   
(1, 0)       0 0.80000       0       0 0.10000       0       0       0   
(1, 1)       0 0.01000       0       0 0.98000       0       0       0   
(2, 0)       0 0.80000       0       0 0.10000       0       0       0   
(2, 1)       0 0.01000       0       0 0.98000       0       0       0   
(2, 2)       0 0.10000       0       0 0.10000       0       0       0   
(3, 0)       0 0.80000       0       0 0.10000       0       0       0   
(3, 1)       0 0.01000       0       0 0.98000       0       0       0   
(3, 2)       0 0.10000       0       0 0.10000       0       0       0   
(4, 0)       0 0.80000       0       0 0.10000       0       0       0   
(4, 1)       0 0.01000       0       0 0.98000       0       0       0   
(4, 2)       0 0.10000       0       0 0.10000       0       0       0   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0) 0.10000       0       0       0  
(1, 0) 0.10000       0       0       0  
(1, 1) 0.01000       0       0       0  
(2, 0) 0.10000       0       0       0  
(2, 1) 0.01000       0       0       0  
(2, 2) 0.80000       0       0       0  
(3, 0) 0.10000       0       0       0  
(3, 1) 0.01000       0       0       0  
(3, 2) 0.80000       0       0       0  
(4, 0) 0.10000       0       0       0  
(4, 1) 0.01000       0       0       0  
(4, 2) 0.80000       0       0       0

For a = 2, s' must be equal to e', therefore, probability on transitioning to (s',e') where s' != e' + 2 should be 0.

In [40]:
#looping through (s', e')
for (s_,e_) in col_name: # s_ and e_ corresponds to columns
    if s_ != e_ + 2:
        Pt_se_df_2.loc[:, (s_,e_)] = 0
        
# transitioning from (s,e) to (s',e') should now only be dependent on transition probability matrix (e,e')
for (s,e) in col_name:
    for(s_,e_) in col_name:
        if Pt_se_df_2.at[(s,e), (s_,e_)] != 0:
            Pt_se_df_2.at[(s,e), (s_,e_)] = Pt_e[e,e_]
            
            
# view result
Pt_se_df_2

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0)       0       0       0 0.80000       0       0       0 0.10000   
(1, 0)       0       0       0 0.80000       0       0       0 0.10000   
(1, 1)       0       0       0 0.01000       0       0       0 0.98000   
(2, 0)       0       0       0 0.80000       0       0       0 0.10000   
(2, 1)       0       0       0 0.01000       0       0       0 0.98000   
(2, 2)       0       0       0 0.10000       0       0       0 0.10000   
(3, 0)       0       0       0 0.80000       0       0       0 0.10000   
(3, 1)       0       0       0 0.01000       0       0       0 0.98000   
(3, 2)       0       0       0 0.10000       0       0       0 0.10000   
(4, 0)       0       0       0 0.80000       0       0       0 0.10000   
(4, 1)       0       0       0 0.01000       0       0       0 0.98000   
(4, 2)       0       0       0 0.10000       0       0       0 0.10000   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0)       0       0       0 0.10000  
(1, 0)       0       0       0 0.10000  
(1, 1)       0       0       0 0.01000  
(2, 0)       0       0       0 0.10000  
(2, 1)       0       0       0 0.01000  
(2, 2)       0       0       0 0.80000  
(3, 0)       0       0       0 0.10000  
(3, 1)       0       0       0 0.01000  
(3, 2)       0       0       0 0.80000  
(4, 0)       0       0       0 0.10000  
(4, 1)       0       0       0 0.01000  
(4, 2)       0       0       0 0.80000

#### 2) The child subjected utility from eating ice cream is log( c + 1) if c ≥ 0 and −∞ otherwise.  Construct the reward matrix for each transition (s, e, a) and (s′, e′).

In [42]:
# construct reward function
def reward(c):
    if c >= 0:
        return np.log(c + 1)
    else:
        return -8.000000000 # placeholder for negative infinity
    

# apply function to get (s, e, a) combos
reward_row = []

for a in range(3):
    for (s,e) in col_name:
        reward_row.append((s,e,a))

# view result
reward_row

[(0, 0, 0),
 (1, 0, 0),
 (1, 1, 0),
 (2, 0, 0),
 (2, 1, 0),
 (2, 2, 0),
 (3, 0, 0),
 (3, 1, 0),
 (3, 2, 0),
 (4, 0, 0),
 (4, 1, 0),
 (4, 2, 0),
 (0, 0, 1),
 (1, 0, 1),
 (1, 1, 1),
 (2, 0, 1),
 (2, 1, 1),
 (2, 2, 1),
 (3, 0, 1),
 (3, 1, 1),
 (3, 2, 1),
 (4, 0, 1),
 (4, 1, 1),
 (4, 2, 1),
 (0, 0, 2),
 (1, 0, 2),
 (1, 1, 2),
 (2, 0, 2),
 (2, 1, 2),
 (2, 2, 2),
 (3, 0, 2),
 (3, 1, 2),
 (3, 2, 2),
 (4, 0, 2),
 (4, 1, 2),
 (4, 2, 2)]

In [45]:
# return 36 X 12 array without initializing entries
R_sea = np.empty((len(reward_row),len(col_name)))

# fill with NaNs
R_sea[:] = np.nan

# overlay column names
R_sea_df = pd.DataFrame(R_sea, columns=col_name, index=reward_row)

# view result
R_sea_df

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2, 0)     nan     nan     nan     nan     nan     nan     nan     nan   
(0, 0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2, 1)     nan     nan     nan     nan     nan     nan     nan     nan   
(0, 0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(1, 1, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 1, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(2, 2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 1, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(3, 2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 0, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 1, 2)     nan     nan     nan     nan     nan     nan     nan     nan   
(4, 2, 2)     nan     nan     nan     nan     nan     nan     nan     nan   

           (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0, 0)     nan     nan     nan     nan  
(1, 0, 0)     nan     nan     nan     nan  
(1, 1, 0)     nan     nan     nan     nan  
(2, 0, 0)     nan     nan     nan     nan  
(2, 1, 0)     nan     nan     nan     nan  
(2, 2, 0)     nan     nan     nan     nan  
(3, 0, 0)     nan     nan     nan     nan  
(3, 1, 0)     nan     nan     nan     nan  
(3, 2, 0)     nan     nan     nan     nan  
(4, 0, 0)     nan     nan     nan     nan  
(4, 1, 0)     nan     nan     nan     nan  
(4, 2, 0)     nan     nan     nan     nan  
(0, 0, 1)     nan     nan     nan     nan  
(1, 0, 1)     nan     nan     nan     nan  
(1, 1, 1)     nan     nan     nan     nan  
(2, 0, 1)     nan     nan     nan     nan  
(2, 1, 1)     nan     nan     nan     nan  
(2, 2, 1)     nan     nan     nan     nan  
(3, 0, 1)     nan     nan     nan     nan  
(3, 1, 1)     nan     nan     nan     nan  
(3, 2, 1)     nan     nan     nan     nan  
(4, 0, 1)     nan     nan     nan     nan  
(4, 1, 1)     nan     nan     nan     nan  
(4, 2, 1)     nan     nan     nan     nan  
(0, 0, 2)     nan     nan     nan     nan  
(1, 0, 2)     nan

In [46]:
# apply reward function 

# reward is dependent on availability of ice cream, s, at the initial state
for (s,e,a) in reward_row:
    c = s - a
    R_sea_df.loc[(s,e,a),:] = reward(c)
    
# view result
R_sea_df

(0, 0)   (1, 0)   (1, 1)   (2, 0)   (2, 1)   (2, 2)   (3, 0)  \
(0, 0, 0)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(1, 0, 0)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(1, 1, 0)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(2, 0, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(2, 1, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(2, 2, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(3, 0, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(3, 1, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(3, 2, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(4, 0, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944   
(4, 1, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944   
(4, 2, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944  1.60944   
(0, 0, 1) -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000   
(1, 0, 1)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(1, 1, 1)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(2, 0, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(2, 1, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(2, 2, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(3, 0, 1)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(3, 1, 1)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(3, 2, 1)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(4, 0, 1)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(4, 1, 1)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(4, 2, 1)  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629  1.38629   
(0, 0, 2) -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000   
(1, 0, 2) -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000   
(1, 1, 2) -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000 -8.00000   
(2, 0, 2)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(2, 1, 2)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(2, 2, 2)  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
(3, 0, 2)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(3, 1, 2)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(3, 2, 2)  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315  0.69315   
(4, 0, 2)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(4, 1, 2)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   
(4, 2, 2)  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861  1.09861   

            (3, 1)   (3, 2)   (4, 0)   (4, 1)   (4, 2)  
(0, 0, 0)  0.00000  0.00000  0.00000  0.00000  0.00000  
(1, 0, 0)  0.69315  0.69315  0.69315  0.69315  0.69315  
(1, 1, 0)  0.69315  0.69315  0.69315  0.69315  0.69315  
(2, 0, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  
(2, 1, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  
(2, 2, 0)  1.09861  1.09861  1.09861  1.09861  1.09861  
(3, 0, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  
(3, 1, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  
(3, 2, 0)  1.38629  1.38629  1.38629  1.38629  1.38629  
(4, 0, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  
(4, 1, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  
(4, 2, 0)  1.60944  1.60944  1.60944  1.60944  1.60944  
(0, 0, 1) -8.00000 -8.00000 -8.00000 -8.00000 -8.00000  
(1, 0, 1)  0.00000  0.00000  0.00000  0.00000  0.00000  
(1, 1, 1)  0.00000  0.00000  0.00000  0.00000  0.00000  
(2, 0, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  
(2, 1, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  
(2, 2, 1)  0.69315  0.69315  0.69315  0.69315  0.69315  
(3, 0, 1)  1.09861  1.09861  1.09861  1.09861  1.09861  
(3, 1, 1)  1.09861  1.09861  1.09861  1.09861  1.09861  
(3

In [47]:
# create a copy of transition probability matrix for analysis of rewards for each action a∈{0, 1, 2}
R_se_df_0 = Pt_se_df.copy()
R_se_df_1 = Pt_se_df.copy()
R_se_df_2 = Pt_se_df.copy()

In [48]:
# reward matrix for all values for a
# eating all the ice cream is (s = c)

a = 0
for (s,e) in col_name:
    c = s - a
    R_se_df_0.loc[(s,e),:] = reward(c)
      
a = 1
for (s,e) in col_name:
    c = s - a
    R_se_df_1.loc[(s,e),:] = reward(c)

a = 2
for (s,e) in col_name:
    c = s - a
    R_se_df_2.loc[(s,e),:] = reward(c)

In [49]:
# immediate expected rewards in 0-2 neighborhood
R_se_df_0

(0, 0)  (1, 0)  (1, 1)  (2, 0)  (2, 1)  (2, 2)  (3, 0)  (3, 1)  \
(0, 0) 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000   
(1, 0) 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315   
(1, 1) 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315 0.69315   
(2, 0) 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861   
(2, 1) 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861   
(2, 2) 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861 1.09861   
(3, 0) 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629   
(3, 1) 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629   
(3, 2) 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629 1.38629   
(4, 0) 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944   
(4, 1) 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944   
(4, 2) 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944 1.60944   

        (3, 2)  (4, 0)  (4, 1)  (4, 2)  
(0, 0) 0.00000 0.00000 0.00000 0.00000  
(1, 0) 0.69315 0.69315 0.69315 0.69315  
(1, 1) 0.69315 0.69315 0.69315 0.69315  
(2, 0) 1.09861 1.09861 1.09861 1.09861  
(2, 1) 1.09861 1.09861 1.09861 1.09861  
(2, 2) 1.09861 1.09861 1.09861 1.09861  
(3, 0) 1.38629 1.38629 1.38629 1.38629  
(3, 1) 1.38629 1.38629 1.38629 1.38629  
(3, 2) 1.38629 1.38629 1.38629 1.38629  
(4, 0) 1.60944 1.60944 1.60944 1.60944  
(4, 1) 1.60944 1.60944 1.60944 1.60944  
(4, 2) 1.60944 1.60944 1.60944 1.60944

In [50]:
# combine all transition probabilities into one array
P = np.array([Pt_se_df_0, Pt_se_df_1, Pt_se_df_2],dtype=float)
P.shape

P

(3, 12, 2)

array([[[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]]])

In [51]:
# combine all rewards into one array
RR = np.array([R_se_df_0, R_se_df_1, R_se_df_2],dtype=float)
RR.shape

RR

(3, 12, 2)

array([[[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [3., 0.],
        [3., 1.],
        [3., 2.],
        [4., 0.],
        [4., 1.],
        [4., 2.]]])

#### 3) Apply the value iteration approach to compute the value function for each state and optimal policy. Iterate 600 times.

In [52]:
K,N,M = P.shape

# instantiate expected reward matrix
q = np.zeros((K,N,1), dtype=np.float64)# create three 12 x 1 arrays
q.shape


# loop through each (K,N,M) array
for i in range(0,N): # N is 12
    for k in range(0,K): # K is 3
        for j in range(0,M): # M is 2
            q[k,i,0] = q[k,i,0] + RR[k,i,j]*P[k,i,j]

# view result
q

(3, 12, 1)

array([[[ 0.],
        [ 1.],
        [ 2.],
        [ 4.],
        [ 5.],
        [ 8.],
        [ 9.],
        [10.],
        [13.],
        [16.],
        [17.],
        [20.]],

       [[ 0.],
        [ 1.],
        [ 2.],
        [ 4.],
        [ 5.],
        [ 8.],
        [ 9.],
        [10.],
        [13.],
        [16.],
        [17.],
        [20.]],

       [[ 0.],
        [ 1.],
        [ 2.],
        [ 4.],
        [ 5.],
        [ 8.],
        [ 9.],
        [10.],
        [13.],
        [16.],
        [17.],
        [20.]]])

In [53]:
# number of episodes
T = 600

# value table
v = np.zeros((N,T),dtype=np.float64) # N is 12
v.shape
v

# decisions table
d = np.zeros((N,T),dtype=np.float64)
d.shape
d

(12, 600)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(12, 600)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [54]:
for n in range(1,T): # T is 600; have to start n at 1 b/c below access n-1 th element
    y0 = 12 # fails without this line
    for i in range(0,N): # N is 12
            if i==y0:
                # rhs should be 1 x 3 and will initially be all zeroes
                rhs = np.zeros((1,K),dtype=np.float64) # K is 3
                for k in range(0,K):
                    # access kth element from rhs; rhs[0] is (0,0,0)
                    # q[k][i][0] accesses actual number within 12-item array
                    rhs[0][k] = q[k][i][0] + np.matmul(P[k,i,:],v[:,n-1]) # P has 3 arrays that are 12 x 2

In [55]:
# value table
v = v.T
v

# decisions table
d = d.T
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.,

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.,

In [56]:
value_data = {'iteration': [*range(T)], 'value (0,0)': v[:,0], 'value (0,1)': v[:,1], 'value (0,2)': v[:,2], 
              'value (1,0)': v[:,3], 'value (1,1)': v[:,4], 'value (1,2)': v[:,5], 'value (2,0)': v[:,6], 
              'value (2,1)': v[:,7], 'value (2,2)': v[:,8], 'value (3,0)': v[:,9], 'value (3,1)': v[:,10], 
              'value (3,2)': v[:,11], 'value (4,0)': v[:,12], 'value (4,1)': v[:,13], 'value (4,2)': v[:,14]}

values = pd.DataFrame(value_data)

values

IndexError: index 12 is out of bounds for axis 1 with size 12

In [ ]:
policy_data = {'iteration': [*range(T)], 'policy (0,0)': v[:,0], 'policy (0,1)': v[:,1], 'policy (0,2)': v[:,2], 
              'policy (1,0)': v[:,3], 'policy (1,1)': v[:,4], 'policy (1,2)': v[:,5], 'policy (2,0)': v[:,6], 
              'policy (2,1)': v[:,7], 'policy (2,2)': v[:,8], 'policy (3,0)': v[:,9], 'policy (3,1)': v[:,10], 
              'policy (3,2)': v[:,11], 'policy (4,0)': v[:,12], 'policy (4,1)': v[:,13], 'policy (4,2)': v[:,14]}

policy = pd.DataFrame(policy_data)

Policy

In [ ]:
policy_df = pd.DataFrame(d, columns=col_name)
policy_df

#### 4) For each e, plot the value function v(s, e) with s on the x-axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

In [ ]:
# take values at bottom of value table you calculate in three for the (s, e) pairs
# look up the value for the different states and scoops given combinations
# can put put none for infeasible states like (0, 1) since can't have 0 if just given a scoop

value_data = pd.DataFrame({'s': range(5),
                          'zero': [],
                          'one': [],
                          'two': []})

In [ ]:
plt.plot('s', 'zero', data = value_data, color = 'blue')
plt.plot('s', 'one', data = value_data, color = 'yellow')
plt.plot('s', 'two', data = value_data, color = 'orange')

plt.legend()
plt.title('Value function by state for each possible scoops given')

#### 5) For each e, plot the optimal policy for storing ice cream scoops a(s, e) with s on the x- axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

In [ ]:
# same as above but for decision data
deicision_data = pd.DataFrame({'s': range(5),
                          'zero': [],
                          'one': [],
                          'two': []})

plt.plot('s', 'zero', data = decision_data, color = 'red')
plt.plot('s', 'one', data = decision_data, color = 'yellow')
plt.plot('s', 'two', data = decision_data, color = 'green')

plt.legend()
plt.title('Value function by state for each possible scoops given')

#### 6) For each e, plot the optimal policy for consuming ice cream scoops c(s, e) with s on the x-axis. (hint: there should be 3 lines plots, one for each e ∈ {0, 1, 2}.)

#### 7) Simulate a sequence of e and set an initial value for s. Given the optimal policy, calculate and plot the evolution of a, c, and s over time.

#### 8) Construct the transition probability and reward matrices between (s, e) and (s′, e′) that produces the highest expected discount rewards. (hint: you need to use the optimal policy)

#### 9) Calculate the value function for the Markok process with rewards that produces the highest expected discount rewards. (hint: use the transition probability and reward matrices from the previous question). Does the value function matches reasonably the value function from the previous question? (hint: it should)

#### 10) Simulate the Markov process with rewards from the previous question for starting at each state pair (e, s). Compute the average discounted reward. Does it match reasonabily close to the value function in the previous question? (hint: it should)

#### 11) Calculate the optimal policy based on the policy iteration approach.